-- ============================================================
-- Quizopia Flyway Migration V1
-- Purpose: Initialize the database foundation.
--
-- This migration does not create business-domain tables.
-- Flyway creates flyway_schema_history automatically.
--
-- Do not modify this file after it has been applied.
-- ============================================================

CREATE TABLE platform_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    metadata_key VARCHAR(100) NOT NULL,
    metadata_value VARCHAR(500) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_platform_metadata_key UNIQUE (metadata_key)
);

INSERT INTO platform_metadata (
    metadata_key,
    metadata_value
)
VALUES
    ('application_name', 'quizopia'),
    ('database_type', 'postgresql'),
    ('schema_stage', 'foundation');