-- ============================================================
-- Quizopia Flyway Migration V2
-- Purpose: Create the Identity and Access Management schema.
--
-- Do not modify this file after it has been applied.
-- ============================================================

-- ============================================================
-- 1. USERS
-- Stores authentication information and account status.
-- Passwords must always be stored as Argon2id hashes.
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(150) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    token_version INTEGER NOT NULL DEFAULT 0,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,

    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'PENDING')),

    CONSTRAINT chk_users_token_version
        CHECK (token_version >= 0),

    CONSTRAINT chk_users_failed_login_attempts
        CHECK (failed_login_attempts >= 0),

    CONSTRAINT chk_users_username_not_blank
        CHECK (LENGTH(TRIM(username)) > 0),

    CONSTRAINT chk_users_email_not_blank
        CHECK (LENGTH(TRIM(email)) > 0),

    CONSTRAINT chk_users_display_name_not_blank
        CHECK (LENGTH(TRIM(display_name)) > 0)
);

CREATE UNIQUE INDEX uk_users_username_ci
    ON users (LOWER(username));

CREATE UNIQUE INDEX uk_users_email_ci
    ON users (LOWER(email));

CREATE INDEX idx_users_status
    ON users (status);

-- ============================================================
-- 2. ROLES
-- Stores the roles used by the Role-Based Access Control model.
-- ============================================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_roles_code UNIQUE (code),

    CONSTRAINT chk_roles_code_not_blank
        CHECK (LENGTH(TRIM(code)) > 0),

    CONSTRAINT chk_roles_name_not_blank
        CHECK (LENGTH(TRIM(name)) > 0),

    CONSTRAINT chk_roles_code_format
        CHECK (code ~ '^[A-Z][A-Z0-9_]*$')
);

-- ============================================================
-- 3. PERMISSIONS
-- Stores fine-grained permissions granted to roles.
-- ============================================================

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_permissions_code UNIQUE (code),

    CONSTRAINT chk_permissions_code_not_blank
        CHECK (LENGTH(TRIM(code)) > 0),

    CONSTRAINT chk_permissions_name_not_blank
        CHECK (LENGTH(TRIM(name)) > 0),

    CONSTRAINT chk_permissions_code_format
        CHECK (code ~ '^[A-Z][A-Z0-9_]*$')
);

-- ============================================================
-- 4. USER_ROLES
-- Assigns one or more roles to a user.
-- ============================================================

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    assigned_by BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_user_roles_expiration
        CHECK (expires_at IS NULL OR expires_at > assigned_at)
);

CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);

CREATE INDEX idx_user_roles_expires_at
    ON user_roles (expires_at)
    WHERE expires_at IS NOT NULL;

-- ============================================================
-- 5. ROLE_PERMISSIONS
-- Grants fine-grained permissions to roles.
-- ============================================================

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,

    granted_by BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_role_permissions
        PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_granted_by
        FOREIGN KEY (granted_by)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_role_permissions_permission_id
    ON role_permissions (permission_id);

-- ============================================================
-- 6. REFRESH_SESSIONS
-- Stores hashed opaque refresh tokens and rotation history.
-- The original refresh token must never be stored.
-- ============================================================

CREATE TABLE refresh_sessions (
    id UUID PRIMARY KEY,

    user_id BIGINT NOT NULL,
    family_id UUID NOT NULL,

    token_hash VARCHAR(64) NOT NULL,

    parent_session_id UUID,
    replaced_by_session_id UUID,

    user_agent VARCHAR(500),
    created_ip INET,
    last_used_ip INET,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,

    revoked_at TIMESTAMPTZ,
    revoke_reason VARCHAR(100),

    CONSTRAINT uk_refresh_sessions_token_hash
        UNIQUE (token_hash),

    CONSTRAINT uk_refresh_sessions_parent
        UNIQUE (parent_session_id),

    CONSTRAINT uk_refresh_sessions_replacement
        UNIQUE (replaced_by_session_id),

    CONSTRAINT fk_refresh_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_refresh_sessions_parent
        FOREIGN KEY (parent_session_id)
        REFERENCES refresh_sessions (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_refresh_sessions_replacement
        FOREIGN KEY (replaced_by_session_id)
        REFERENCES refresh_sessions (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_refresh_sessions_token_hash
        CHECK (
            LENGTH(token_hash) = 64
            AND token_hash ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT chk_refresh_sessions_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT chk_refresh_sessions_last_used
        CHECK (
            last_used_at IS NULL
            OR last_used_at >= created_at
        ),

    CONSTRAINT chk_refresh_sessions_revocation_time
        CHECK (
            revoked_at IS NULL
            OR revoked_at >= created_at
        ),

    CONSTRAINT chk_refresh_sessions_revocation_reason
        CHECK (
            (revoked_at IS NULL AND revoke_reason IS NULL)
            OR
            (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL)
        ),

    CONSTRAINT chk_refresh_sessions_parent_not_self
        CHECK (
            parent_session_id IS NULL
            OR parent_session_id <> id
        ),

    CONSTRAINT chk_refresh_sessions_replacement_not_self
        CHECK (
            replaced_by_session_id IS NULL
            OR replaced_by_session_id <> id
        ),

    CONSTRAINT chk_refresh_sessions_replacement_revoked
        CHECK (
            replaced_by_session_id IS NULL
            OR revoked_at IS NOT NULL
        )
);

CREATE INDEX idx_refresh_sessions_user_id
    ON refresh_sessions (user_id);

CREATE INDEX idx_refresh_sessions_family_id
    ON refresh_sessions (family_id);

CREATE INDEX idx_refresh_sessions_expires_at
    ON refresh_sessions (expires_at);

CREATE INDEX idx_refresh_sessions_active_user
    ON refresh_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_refresh_sessions_active_family
    ON refresh_sessions (family_id)
    WHERE revoked_at IS NULL;