-- ============================================================
-- Quizopia Flyway Migration V7
-- Purpose: Question Bank schema for MVP (4 tables) supporting
--   the 4 approved question types.
--   question_banks, questions, question_versions, question_options
--
-- Design (approved, see .claude/docs/day-5-v6-v7-schema-impact-design.md):
--   - question_type CHECK overrides docs/database.md: TRUE_FALSE/ESSAY
--     removed; TRUE_FALSE_MATRIX + NUMERIC_FILL added.
--   - question_banks.school_id + composite FKs enforce that the subject
--     and the owner teacher are in the SAME school as the bank.
--   - default_points NUMERIC(10,2) CHECK > 0 (renamed from default_score).
--   - NUMERIC_FILL answer_key CHECK is type-safe: it distinguishes JSON
--     number 4 from JSON string "4" via jsonb-vs-jsonb comparison, and
--     requires a non-blank roundingInstruction.
--   - PK = BIGINT GENERATED BY DEFAULT AS IDENTITY.
--
-- Do not modify V1–V6. Do not modify this file after it has been applied.
-- ============================================================

-- 1. QUESTION_BANKS (school_id denormalized; subject + owner same school via composite FK)
CREATE TABLE question_banks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT       NOT NULL,
    subject_id        BIGINT       NOT NULL,
    owner_teacher_id  BIGINT       NOT NULL,
    code              VARCHAR(80)  NOT NULL,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    visibility        VARCHAR(30)  NOT NULL DEFAULT 'PRIVATE',
    status            VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite FK: subject MUST be in the SAME school as the bank.
    CONSTRAINT fk_question_banks_subject_school
        FOREIGN KEY (school_id, subject_id) REFERENCES subjects (school_id, id) ON DELETE RESTRICT,
    -- Composite FK: owner teacher MUST be in the SAME school as the bank.
    CONSTRAINT fk_question_banks_owner_school
        FOREIGN KEY (school_id, owner_teacher_id) REFERENCES teacher_profiles (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_question_banks_visibility CHECK (visibility IN ('PRIVATE','SHARED','PUBLIC')),
    CONSTRAINT chk_question_banks_status CHECK (status IN ('ACTIVE','ARCHIVED')),
    CONSTRAINT chk_question_banks_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_question_banks_name_not_blank CHECK (LENGTH(TRIM(name)) > 0)
);
CREATE UNIQUE INDEX uk_question_banks_owner_code_ci
    ON question_banks (owner_teacher_id, LOWER(code));
CREATE INDEX idx_question_banks_subject_id ON question_banks (subject_id);

-- 2. QUESTIONS (stable identity in a bank)
CREATE TABLE questions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_bank_id       BIGINT      NOT NULL,
    code                   VARCHAR(80) NOT NULL,
    current_version_number INTEGER     NOT NULL DEFAULT 1,
    status                 VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by             BIGINT      NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_questions_bank
        FOREIGN KEY (question_bank_id) REFERENCES question_banks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_questions_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_questions_current_version CHECK (current_version_number > 0),
    CONSTRAINT chk_questions_status CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')),
    CONSTRAINT chk_questions_code_not_blank CHECK (LENGTH(TRIM(code)) > 0)
);
CREATE UNIQUE INDEX uk_questions_bank_code_ci ON questions (question_bank_id, LOWER(code));

-- 3. QUESTION_VERSIONS (immutable; default_points; NUMERIC answer_key checks)
CREATE TABLE question_versions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id    BIGINT      NOT NULL,
    version_number INTEGER     NOT NULL,
    question_type  VARCHAR(40) NOT NULL,
    content        TEXT        NOT NULL,
    explanation    TEXT,
    difficulty     VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    default_points NUMERIC(10,2) NOT NULL DEFAULT 1,
    answer_key     JSONB,
    metadata       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_by     BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_versions_question
        FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_question_versions_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_question_versions_version CHECK (version_number > 0),
    CONSTRAINT chk_question_versions_type
        CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE_MATRIX','NUMERIC_FILL')),
    CONSTRAINT chk_question_versions_difficulty
        CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT chk_question_versions_default_points CHECK (default_points > 0),
    CONSTRAINT chk_question_versions_content_not_blank CHECK (LENGTH(TRIM(content)) > 0),
    -- answer_key present iff NUMERIC_FILL; both answer_key (when present) and metadata must be JSON objects.
    CONSTRAINT chk_question_versions_answer_key_presence
        CHECK ((question_type = 'NUMERIC_FILL') = (answer_key IS NOT NULL)),
    CONSTRAINT chk_question_versions_answer_key_object
        CHECK (answer_key IS NULL OR jsonb_typeof(answer_key) = 'object'),
    CONSTRAINT chk_question_versions_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object'),
    -- NUMERIC_FILL answer_key: simplified to require only expectedAnswer
    -- (absorbed from legacy V12 — requiredInputLength/roundingInstruction
    --  are frontend/UI concerns, no longer stored in the answer_key JSON).
    CONSTRAINT chk_question_versions_numeric_answer_key
        CHECK (
            question_type <> 'NUMERIC_FILL'
            OR (
                answer_key ? 'expectedAnswer'
                AND jsonb_typeof(answer_key -> 'expectedAnswer') = 'string'
                AND LENGTH(answer_key ->> 'expectedAnswer') = 4
                AND answer_key ->> 'expectedAnswer' ~ '^-?[0-9]+([.][0-9]+)?$'
            )
        ),
    -- Composite unique for FK target from exam_questions (moved from V8 ALTER).
    CONSTRAINT uk_question_versions_question_id UNIQUE (question_id, id)
);
CREATE UNIQUE INDEX uk_question_versions_question_version
    ON question_versions (question_id, version_number);

-- 4. QUESTION_OPTIONS (option_key A-F; SINGLE/MULTIPLE A-F, TRUE_FALSE_MATRIX A-D enforced in app)
CREATE TABLE question_options (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_version_id BIGINT      NOT NULL,
    option_key          VARCHAR(20) NOT NULL,
    content             TEXT        NOT NULL,
    is_correct          BOOLEAN     NOT NULL DEFAULT FALSE,
    position            INTEGER     NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_options_version
        FOREIGN KEY (question_version_id) REFERENCES question_versions(id) ON DELETE CASCADE,
    CONSTRAINT chk_question_options_key CHECK (option_key IN ('A','B','C','D','E','F')),
    CONSTRAINT chk_question_options_position CHECK (position >= 0),
    CONSTRAINT chk_question_options_content_not_blank CHECK (LENGTH(TRIM(content)) > 0)
);
CREATE UNIQUE INDEX uk_question_options_version_key
    ON question_options (question_version_id, option_key);
CREATE UNIQUE INDEX uk_question_options_version_position
    ON question_options (question_version_id, position);
