-- ============================================================
-- Quizopia Flyway Migration V6
-- Purpose: Trimmed Academic schema for MVP (5 tables).
--   schools, grade_levels, subjects, teacher_profiles, student_profiles
--
-- Design (approved, see .claude/docs/day-5-v6-v7-schema-impact-design.md):
--   - School scope enforced at DB via composite FK + UNIQUE (school_id, id).
--   - subjects -> grade_levels via composite FK so a grade_level MUST be in
--     the same school as the subject.
--   - PK = BIGINT GENERATED BY DEFAULT AS IDENTITY (consistent with users V2).
--   - Deferred (NOT in MVP): classrooms, classroom_memberships, teacher_subjects.
--
-- Do not modify V1–V5. Do not modify this file after it has been applied.
-- ============================================================

-- 1. SCHOOLS (school scope root)
CREATE TABLE schools (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(50)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    address    VARCHAR(500),
    timezone   VARCHAR(80)  NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    status     VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_schools_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT chk_schools_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_schools_name_not_blank CHECK (LENGTH(TRIM(name)) > 0)
);
CREATE UNIQUE INDEX uk_schools_code_ci ON schools (LOWER(code));

-- 2. GRADE_LEVELS (belong to school)
CREATE TABLE grade_levels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT       NOT NULL,
    code       VARCHAR(30)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grade_levels_school
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT chk_grade_levels_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_grade_levels_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    -- Target of composite FK from subjects:
    CONSTRAINT uk_grade_levels_school_id UNIQUE (school_id, id)
);
CREATE UNIQUE INDEX uk_grade_levels_school_code_ci ON grade_levels (school_id, LOWER(code));

-- 3. SUBJECTS (belong to school + grade_level; composite FK guarantees same school)
CREATE TABLE subjects (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id      BIGINT       NOT NULL,
    grade_level_id BIGINT       NOT NULL,
    code           VARCHAR(50)  NOT NULL,
    name           VARCHAR(150) NOT NULL,
    description    TEXT,
    status         VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite FK: grade_level MUST be in the SAME school.
    CONSTRAINT fk_subjects_grade_level_school
        FOREIGN KEY (school_id, grade_level_id) REFERENCES grade_levels (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_subjects_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT chk_subjects_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    -- Target of composite FK from question_banks (V7):
    CONSTRAINT uk_subjects_school_id UNIQUE (school_id, id)
);
CREATE UNIQUE INDEX uk_subjects_school_grade_code_ci
    ON subjects (school_id, grade_level_id, LOWER(code));

-- 4. TEACHER_PROFILES (1-1 with users; belong to school)
CREATE TABLE teacher_profiles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    school_id         BIGINT      NOT NULL,
    teacher_code      VARCHAR(50) NOT NULL,
    title             VARCHAR(100),
    employment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teacher_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_teacher_profiles_school
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT chk_teacher_profiles_status
        CHECK (employment_status IN ('ACTIVE','INACTIVE','ON_LEAVE','TERMINATED')),
    CONSTRAINT chk_teacher_profiles_code_not_blank CHECK (LENGTH(TRIM(teacher_code)) > 0),
    CONSTRAINT uk_teacher_profiles_user UNIQUE (user_id),
    -- Target of composite FK from question_banks (V7):
    CONSTRAINT uk_teacher_profiles_school_id UNIQUE (school_id, id)
);
CREATE UNIQUE INDEX uk_teacher_profiles_school_code_ci
    ON teacher_profiles (school_id, LOWER(teacher_code));

-- 5. STUDENT_PROFILES (1-1 with users; belong to school)
CREATE TABLE student_profiles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    school_id         BIGINT      NOT NULL,
    student_code      VARCHAR(50) NOT NULL,
    enrollment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_profiles_school
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT chk_student_profiles_status
        CHECK (enrollment_status IN ('ACTIVE','INACTIVE','GRADUATED','WITHDRAWN')),
    CONSTRAINT chk_student_profiles_code_not_blank CHECK (LENGTH(TRIM(student_code)) > 0),
    CONSTRAINT uk_student_profiles_user UNIQUE (user_id),
    -- Target of future composite FK from exam_session_participants (V8):
    CONSTRAINT uk_student_profiles_school_id UNIQUE (school_id, id)
);
CREATE UNIQUE INDEX uk_student_profiles_school_code_ci
    ON student_profiles (school_id, LOWER(student_code));
