-- ============================================================
-- Quizopia Flyway Migration V7
-- Purpose: Attempt & Grading schema for MVP Day 7 (6 tables).
--   attempts, attempt_questions, attempt_answers, grades, grade_items,
--   idempotency_records
--
-- Design (FROZEN, see .claude/docs/day-7-v9-schema-impact-design.md — A1.2):
--   - Independent: NO ALTER to V1–V8. Only CREATE TABLE + indexes on new tables.
--   - Composite same-school FKs on attempts (session + student); single-column FK
--     to exam_questions/exam_versions (cross-version safety is application-layer).
--   - Composite ownership FKs:
--       attempt_questions UNIQUE (attempt_id, id)  -> target for attempt_answers/grade_items.
--       grades            UNIQUE (id, attempt_id)  -> target for grade_items.
--       attempt_answers   (attempt_id, attempt_question_id) -> attempt_questions(attempt_id, id) CASCADE.
--       grade_items       (grade_id, attempt_id)             -> grades(id, attempt_id) CASCADE.
--       grade_items       (attempt_id, attempt_question_id)  -> attempt_questions(attempt_id, id) RESTRICT.
--   - Submission invariant (D25): status <-> submitted_at <-> submission_idempotency_key.
--   - One active attempt: partial UNIQUE (session, student) WHERE status = 'IN_PROGRESS'.
--   - Submit key: partial UNIQUE (student, submission_idempotency_key) WHERE key IS NOT NULL.
--   - attempt_answers.sequence_number >= 1 (strictly-greater UPSERT guard in app).
--   - grades: score caps (auto/final <= max), RELEASED iff released_at, graded_by RESTRICT.
--   - grade_items: attempt-scoped (attempt_question_id, NOT exam_question_id),
--     awarded_points <= max_points, is_correct NOT NULL.
--   - idempotency_records: attempt-scoped; operation = 'ATTEMPT_SUBMIT'; response_status = 200;
--     response_body JSONB NOT NULL object; expires_at forced NULL (MVP); no request_hash;
--     UNIQUE (user_id, operation, idempotency_key) blocks cross-attempt key reuse;
--     UNIQUE (attempt_id, operation) enforces exactly one cached submit per attempt.
--
-- Do not modify V1–V8. Do not modify this file after it has been applied.
-- ============================================================

-- 1. attempts
CREATE TABLE attempts (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id                   BIGINT       NOT NULL,
    exam_session_id             BIGINT       NOT NULL,
    student_profile_id          BIGINT       NOT NULL,
    exam_version_id             BIGINT       NOT NULL,
    attempt_number              INTEGER      NOT NULL,
    status                      VARCHAR(30)  NOT NULL DEFAULT 'IN_PROGRESS',
    started_at                  TIMESTAMPTZ  NOT NULL,
    deadline_at                 TIMESTAMPTZ  NOT NULL,
    submitted_at                TIMESTAMPTZ,
    last_saved_at               TIMESTAMPTZ,
    client_instance_id          UUID,
    submission_idempotency_key  VARCHAR(100),
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite same-school FKs (mirror V8 pattern; targets already exist on V6/V8 tables).
    CONSTRAINT fk_attempts_session_school
        FOREIGN KEY (school_id, exam_session_id) REFERENCES exam_sessions(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_attempts_student_school
        FOREIGN KEY (school_id, student_profile_id) REFERENCES student_profiles(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_attempts_version
        FOREIGN KEY (exam_version_id) REFERENCES exam_versions(id) ON DELETE RESTRICT,
    CONSTRAINT chk_attempts_status
        CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'GRADED')),
    CONSTRAINT chk_attempts_number
        CHECK (attempt_number > 0),
    CONSTRAINT chk_attempts_deadline
        CHECK (deadline_at >= started_at),
    -- A1.2 D25: status <-> submitted_at <-> submission_idempotency_key (all three together).
    CONSTRAINT chk_attempts_submission_invariant CHECK (
        (status = 'IN_PROGRESS'     AND submitted_at IS NULL AND submission_idempotency_key IS NULL)
        OR
        (status IN ('SUBMITTED','GRADED') AND submitted_at IS NOT NULL AND submission_idempotency_key IS NOT NULL)
    ),
    -- One attempt per (session, student, number).
    CONSTRAINT uk_attempts_session_student_number UNIQUE (exam_session_id, student_profile_id, attempt_number)
);
-- At most one IN_PROGRESS attempt per (session, student). [D1]
CREATE UNIQUE INDEX uk_attempts_one_active_per_session_student
    ON attempts (exam_session_id, student_profile_id) WHERE status = 'IN_PROGRESS';
-- Submit key unique per student (NULLs exempt — PostgreSQL partial index). [D10]
CREATE UNIQUE INDEX uk_attempts_student_submit_key
    ON attempts (student_profile_id, submission_idempotency_key) WHERE submission_idempotency_key IS NOT NULL;
-- Query paths: active count per session; per-student history; per (session, student).
CREATE INDEX idx_attempts_session_status ON attempts (exam_session_id, status);
CREATE INDEX idx_attempts_student ON attempts (student_profile_id);
CREATE INDEX idx_attempts_session_student ON attempts (exam_session_id, student_profile_id);

-- 2. attempt_questions  (stable order snapshot; question_type/default_points denormalized; UQ (attempt_id, id) target)
CREATE TABLE attempt_questions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id       BIGINT        NOT NULL,
    exam_question_id BIGINT        NOT NULL,
    question_type    VARCHAR(40)   NOT NULL,
    default_points   NUMERIC(10,2) NOT NULL,
    display_order    INTEGER       NOT NULL,
    option_order     JSONB,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attempt_questions_attempt
        FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
    -- Single-column; cross-version safety is enforced at the application layer (schema §11).
    CONSTRAINT fk_attempt_questions_exam
        FOREIGN KEY (exam_question_id) REFERENCES exam_questions(id) ON DELETE RESTRICT,
    CONSTRAINT chk_attempt_questions_type
        CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE_MATRIX','NUMERIC_FILL')),
    CONSTRAINT chk_attempt_questions_points CHECK (default_points > 0),
    CONSTRAINT chk_attempt_questions_order CHECK (display_order >= 0),
    CONSTRAINT chk_attempt_questions_option_order
        CHECK (option_order IS NULL OR jsonb_typeof(option_order) = 'array'),
    -- Composite target for attempt_answers/grade_items ownership FKs. [D17]
    CONSTRAINT uk_attempt_questions_attempt_id UNIQUE (attempt_id, id),
    CONSTRAINT uk_attempt_questions_attempt_exam UNIQUE (attempt_id, exam_question_id),
    CONSTRAINT uk_attempt_questions_attempt_order UNIQUE (attempt_id, display_order)
);
CREATE INDEX idx_attempt_questions_exam ON attempt_questions (exam_question_id);

-- 3. attempt_answers  (UPSERT sequence guard >=1; composite ownership FK [D17])
CREATE TABLE attempt_answers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT      NOT NULL,
    attempt_question_id BIGINT      NOT NULL,
    answer_payload      JSONB,
    sequence_number     BIGINT      NOT NULL,
    saved_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Direct cascade when the attempt is deleted.
    CONSTRAINT fk_attempt_answers_attempt
        FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
    -- Composite ownership: pins the answer to the (attempt, attempt_question) pair, so an answer
    -- cannot reference an attempt_question belonging to a different attempt. [D17]
    CONSTRAINT fk_attempt_answers_question_attempt
        FOREIGN KEY (attempt_id, attempt_question_id) REFERENCES attempt_questions(attempt_id, id) ON DELETE CASCADE,
    -- sequence_number >= 1 (app performs strictly-greater UPSERT). [D6]
    CONSTRAINT chk_attempt_answers_seq CHECK (sequence_number >= 1),
    CONSTRAINT chk_attempt_answers_payload
        CHECK (answer_payload IS NULL OR jsonb_typeof(answer_payload) = 'object'),
    CONSTRAINT uk_attempt_answers_attempt_question UNIQUE (attempt_id, attempt_question_id)
);

-- 4. grades  (table created V9; Day 8 writes; UQ (id, attempt_id) target; score<=max; RELEASED iff released_at; graded_by RESTRICT)
CREATE TABLE grades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id      BIGINT        NOT NULL,
    automatic_score NUMERIC(10,2) NOT NULL,
    final_score     NUMERIC(10,2) NOT NULL,
    max_score       NUMERIC(10,2) NOT NULL,
    percentage      NUMERIC(7,4),
    status          VARCHAR(30)   NOT NULL DEFAULT 'AUTO_GRADED',
    graded_at       TIMESTAMPTZ   NOT NULL,
    released_at     TIMESTAMPTZ,
    graded_by       BIGINT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grades_attempt
        FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE RESTRICT,
    -- RESTRICT (not SET NULL): preserve grading integrity. [D18]
    CONSTRAINT fk_grades_graded_by
        FOREIGN KEY (graded_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_grades_auto  CHECK (automatic_score >= 0 AND automatic_score <= max_score),
    CONSTRAINT chk_grades_final CHECK (final_score >= 0 AND final_score <= max_score),
    CONSTRAINT chk_grades_max   CHECK (max_score > 0),
    CONSTRAINT chk_grades_percentage CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 100)),
    CONSTRAINT chk_grades_status CHECK (status IN ('AUTO_GRADED','RELEASED')),
    -- RELEASED iff released_at is non-null. [D18]
    CONSTRAINT chk_grades_released_invariant CHECK ((status = 'RELEASED') = (released_at IS NOT NULL)),
    -- Exactly one grade per attempt (anti-double-grade).
    CONSTRAINT uk_grades_attempt UNIQUE (attempt_id),
    -- Composite target for grade_items ownership FK. [D18]
    CONSTRAINT uk_grades_id_attempt UNIQUE (id, attempt_id)
);

-- 5. grade_items  (table created V9; Day 8 writes; attempt-scoped via attempt_questions [D18])
CREATE TABLE grade_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id            BIGINT        NOT NULL,
    attempt_id          BIGINT        NOT NULL,
    attempt_question_id BIGINT        NOT NULL,
    awarded_points      NUMERIC(10,2) NOT NULL,
    max_points          NUMERIC(10,2) NOT NULL,
    is_correct          BOOLEAN       NOT NULL,
    grading_details     JSONB         NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite ownership: pins item to the (grade, attempt) pair.
    CONSTRAINT fk_grade_items_grade_attempt
        FOREIGN KEY (grade_id, attempt_id) REFERENCES grades(id, attempt_id) ON DELETE CASCADE,
    -- Composite ownership: attempt-scoped question (NOT exam_question_id). [D18]
    CONSTRAINT fk_grade_items_attempt_question
        FOREIGN KEY (attempt_id, attempt_question_id) REFERENCES attempt_questions(attempt_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_grade_items_awarded CHECK (awarded_points >= 0 AND awarded_points <= max_points),
    CONSTRAINT chk_grade_items_max CHECK (max_points > 0),
    CONSTRAINT chk_grade_items_details CHECK (jsonb_typeof(grading_details) = 'object'),
    CONSTRAINT uk_grade_items_grade_attempt_question UNIQUE (grade_id, attempt_question_id)
);

-- 6. idempotency_records  (A1.2: attempt_id, exact CHECKs, response_body NOT NULL object, no request_hash,
--    UQ (attempt_id, operation), expires_at forced NULL MVP, no expires index)
CREATE TABLE idempotency_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    attempt_id      BIGINT      NOT NULL,
    operation       VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    response_status INTEGER     NOT NULL,
    response_body   JSONB       NOT NULL,
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_idempotency_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_idempotency_attempt
        FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE RESTRICT,
    -- operation is pinned to ATTEMPT_SUBMIT for MVP. [D19]
    CONSTRAINT chk_idempotency_operation CHECK (operation = 'ATTEMPT_SUBMIT'),
    -- Only success responses are cached. [D19]
    CONSTRAINT chk_idempotency_status CHECK (response_status = 200),
    -- Cached response is always a JSON object (SubmitResponse). [D8]
    CONSTRAINT chk_idempotency_body CHECK (jsonb_typeof(response_body) = 'object'),
    -- A1.2 D26: MVP never expires a submit cache; retention policy would require a later migration.
    CONSTRAINT chk_idempotency_no_expiry CHECK (expires_at IS NULL),
    -- Block reuse of the same (user, operation, key) across attempts. [D19]
    CONSTRAINT uk_idempotency_user_operation_key UNIQUE (user_id, operation, idempotency_key),
    -- Exactly one cached submit response per attempt. [D26]
    CONSTRAINT uk_idempotency_attempt_operation UNIQUE (attempt_id, operation)
);
