-- ============================================================
-- Quizopia Flyway Migration V8
-- Purpose: Exam schema for MVP (8 tables).
--   exam_purposes, exams, exam_versions, exam_sections,
--   exam_questions, exam_question_options, exam_sessions,
--   exam_session_participants
--
-- Design (FROZEN, see .claude/docs/day-6-v8-schema-impact-design.md):
--   - question_type CHECK: 4 approved types only (mirrors V7).
--   - Composite FKs enforce same-school (subject/owner/purpose/version/student)
--     exactly like V6/V7; UNIQUE (school_id, id) targets.
--   - Source snapshot: exam_questions.source_question_id + source_question_version_id
--     NOT NULL; pinned at PUT composition (immutable for grading). Composite FK
--     (source_question_id, source_question_version_id) -> question_versions(question_id, id)
--     enforces provenance (version belongs to question) [H1 remediation].
--   - exam_section_id NOT NULL; question position is LOCAL per section.
--   - Code uniqueness is OWNER-scoped (owner_teacher_id, LOWER(code))
--     for both exams and exam_sessions.
--   - tf_matrix_scoring JSONB exact-object CHECK (fixed shared ladder).
--   - Published invariant CHECK on exam_versions.
--   - M1: exam_sessions status<->opened_at/closed_at CHECK (frozen state machine).
--   - M2: exam_session_participants status<->blocked_at CHECK.
--   - Seeds 4 default exam purposes per existing school (idempotent).
--
-- Do not modify V1–V7. Do not modify this file after it has been applied.
-- ============================================================

-- 1. EXAM_PURPOSES (school scope; TEACHER read-only; seeded)
CREATE TABLE exam_purposes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT       NOT NULL,
    code       VARCHAR(50)  NOT NULL,
    title      VARCHAR(150) NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_purposes_school
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_purposes_position CHECK (position >= 0),
    CONSTRAINT chk_exam_purposes_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_exam_purposes_title_not_blank CHECK (LENGTH(TRIM(title)) > 0),
    -- Composite-FK target for exams.purpose_id.
    CONSTRAINT uk_exam_purposes_school_id UNIQUE (school_id, id)
);
CREATE UNIQUE INDEX uk_exam_purposes_school_code_ci
    ON exam_purposes (school_id, LOWER(code));
CREATE INDEX idx_exam_purposes_school_position
    ON exam_purposes (school_id, position);

-- 2. EXAMS (stable identity; no question content here)
CREATE TABLE exams (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id              BIGINT       NOT NULL,
    subject_id             BIGINT       NOT NULL,
    owner_teacher_id       BIGINT       NOT NULL,
    purpose_id             BIGINT,
    code                   VARCHAR(80)  NOT NULL,
    title                  VARCHAR(255) NOT NULL,
    description            TEXT,
    current_version_number INTEGER      NOT NULL DEFAULT 1,
    status                 VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
    version                INTEGER      NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite FK: subject MUST be in the SAME school as the exam.
    CONSTRAINT fk_exams_subject_school
        FOREIGN KEY (school_id, subject_id) REFERENCES subjects(school_id, id) ON DELETE RESTRICT,
    -- Composite FK: owner teacher MUST be in the SAME school as the exam.
    CONSTRAINT fk_exams_owner_school
        FOREIGN KEY (school_id, owner_teacher_id) REFERENCES teacher_profiles(school_id, id) ON DELETE RESTRICT,
    -- Composite FK: purpose (nullable) MUST be in the SAME school when present. RESTRICT.
    CONSTRAINT fk_exams_purpose_school
        FOREIGN KEY (school_id, purpose_id) REFERENCES exam_purposes(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_exams_status CHECK (status IN ('DRAFT','READY')),
    CONSTRAINT chk_exams_current_version CHECK (current_version_number > 0),
    CONSTRAINT chk_exams_version CHECK (version >= 0),
    CONSTRAINT chk_exams_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_exams_title_not_blank CHECK (LENGTH(TRIM(title)) > 0),
    -- Composite-FK target for exam_versions.exam_id.
    CONSTRAINT uk_exams_school_id UNIQUE (school_id, id)
);
-- Exam code is OWNER-scoped (two teachers in the same school may share a code).
CREATE UNIQUE INDEX uk_exams_owner_code_ci
    ON exams (owner_teacher_id, LOWER(code));
CREATE INDEX idx_exams_owner_created
    ON exams (owner_teacher_id, created_at);
CREATE INDEX idx_exams_subject
    ON exams (subject_id);
CREATE INDEX idx_exams_status
    ON exams (status);

-- 3. EXAM_VERSIONS (version/snapshot; PUBLISHED is immutable)
CREATE TABLE exam_versions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT        NOT NULL,
    exam_id            BIGINT        NOT NULL,
    version_number     INTEGER       NOT NULL,
    title              VARCHAR(255),
    instructions       TEXT,
    duration_minutes   INTEGER       NOT NULL DEFAULT 60,
    total_points       NUMERIC(10,2) NOT NULL DEFAULT 0,
    -- Exact shared TF_MATRIX scoring ladder (snapshot, immutable on publish).
    tf_matrix_scoring  JSONB         NOT NULL DEFAULT '{"0":0,"1":10,"2":25,"3":50,"4":100}'::jsonb,
    status             VARCHAR(30)   NOT NULL DEFAULT 'DRAFT',
    published_at       TIMESTAMPTZ,
    created_by         BIGINT        NOT NULL,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_versions_exam_school
        FOREIGN KEY (school_id, exam_id) REFERENCES exams(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_versions_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_versions_status CHECK (status IN ('DRAFT','PUBLISHED')),
    CONSTRAINT chk_exam_versions_version CHECK (version_number > 0),
    CONSTRAINT chk_exam_versions_duration CHECK (duration_minutes > 0),
    CONSTRAINT chk_exam_versions_total_points CHECK (total_points >= 0),
    -- Exact-object equality; JSONB canonicalization makes key order/whitespace irrelevant.
    CONSTRAINT chk_exam_versions_tf_exact
        CHECK (tf_matrix_scoring = '{"0":0,"1":10,"2":25,"3":50,"4":100}'::jsonb),
    -- Published invariant: DRAFT -> published_at NULL; PUBLISHED -> published_at NOT NULL and points > 0.
    CONSTRAINT chk_exam_versions_published_invariants CHECK (
        (status = 'DRAFT' AND published_at IS NULL)
        OR (status = 'PUBLISHED' AND published_at IS NOT NULL AND total_points > 0)
    ),
    CONSTRAINT uk_exam_versions_exam_version UNIQUE (exam_id, version_number),
    -- Composite-FK target for exam_sessions.exam_version_id.
    CONSTRAINT uk_exam_versions_school_id UNIQUE (school_id, id)
);
-- At most one DRAFT per exam (concurrent publish/create-next-draft guard).
CREATE UNIQUE INDEX uk_exam_versions_one_draft_per_exam
    ON exam_versions (exam_id) WHERE status = 'DRAFT';
CREATE INDEX idx_exam_versions_exam_status
    ON exam_versions (exam_id, status);

-- 4. EXAM_SECTIONS (mandatory container for every exam_question)
CREATE TABLE exam_sections (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_version_id BIGINT       NOT NULL,
    code            VARCHAR(80),
    title           VARCHAR(255) NOT NULL,
    instructions    TEXT,
    position        INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_sections_version
        FOREIGN KEY (exam_version_id) REFERENCES exam_versions(id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_sections_position CHECK (position >= 0),
    CONSTRAINT chk_exam_sections_title_not_blank CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT uk_exam_sections_version_position UNIQUE (exam_version_id, position),
    -- Composite-FK target for exam_questions.exam_section_id.
    CONSTRAINT uk_exam_sections_version_id UNIQUE (exam_version_id, id)
);

-- H1 remediation: composite-FK target on question_versions (added here in V8; V7 file untouched).
-- exam_questions then references (question_id, id) so a pinned source version MUST belong to its
-- source question (provenance), exactly mirroring the same-school composite-FK pattern.
ALTER TABLE question_versions
    ADD CONSTRAINT uk_question_versions_question_id UNIQUE (question_id, id);

-- 5. EXAM_QUESTIONS (immutable snapshot for attempt/grading; source version PINNED)
CREATE TABLE exam_questions (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_version_id            BIGINT        NOT NULL,
    exam_section_id            BIGINT        NOT NULL,
    source_question_id         BIGINT        NOT NULL,
    source_question_version_id BIGINT        NOT NULL,
    question_code              VARCHAR(80)   NOT NULL,
    question_type              VARCHAR(40)   NOT NULL,
    content                    TEXT          NOT NULL,
    default_points             NUMERIC(10,2) NOT NULL,
    difficulty                 VARCHAR(20),
    explanation                TEXT,
    answer_key                 JSONB,
    metadata                   JSONB         NOT NULL DEFAULT '{}'::jsonb,
    position                   INTEGER       NOT NULL,
    created_at                 TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_questions_version
        FOREIGN KEY (exam_version_id) REFERENCES exam_versions(id) ON DELETE RESTRICT,
    -- Composite FK guarantees the section belongs to the SAME version (no cross-version section).
    CONSTRAINT fk_exam_questions_section_version
        FOREIGN KEY (exam_version_id, exam_section_id) REFERENCES exam_sections(exam_version_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_questions_source_question
        FOREIGN KEY (source_question_id) REFERENCES questions(id) ON DELETE RESTRICT,
    -- Composite FK (H1 remediation): the pinned source version MUST belong to the source question.
    -- Replaces the former single-column source_question_version_id -> question_versions(id).
    CONSTRAINT fk_exam_questions_source_pair
        FOREIGN KEY (source_question_id, source_question_version_id)
        REFERENCES question_versions(question_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_questions_type
        CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE_MATRIX','NUMERIC_FILL')),
    CONSTRAINT chk_exam_questions_points CHECK (default_points > 0),
    CONSTRAINT chk_exam_questions_position CHECK (position >= 0),
    CONSTRAINT chk_exam_questions_difficulty
        CHECK (difficulty IS NULL OR difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT chk_exam_questions_code_not_blank CHECK (LENGTH(TRIM(question_code)) > 0),
    CONSTRAINT chk_exam_questions_content_not_blank CHECK (LENGTH(TRIM(content)) > 0),
    -- answer_key present iff NUMERIC_FILL; both answer_key (when present) and metadata must be JSON objects.
    CONSTRAINT chk_exam_questions_answer_presence
        CHECK ((question_type = 'NUMERIC_FILL') = (answer_key IS NOT NULL)),
    CONSTRAINT chk_exam_questions_answer_object
        CHECK (answer_key IS NULL OR jsonb_typeof(answer_key) = 'object'),
    CONSTRAINT chk_exam_questions_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
    -- NUMERIC_FILL answer_key: required keys + type-safe JSON checks + non-blank roundingInstruction.
    -- Type-safe requiredInputLength: answer_key->'requiredInputLength' = '4'::jsonb distinguishes
    -- JSON number 4 from JSON string "4". Representation/trailing zeros preserved (no strip).
    CONSTRAINT chk_exam_questions_numeric_answer_key
        CHECK (
            question_type <> 'NUMERIC_FILL'
            OR (
                answer_key ? 'expectedAnswer'
                AND answer_key ? 'requiredInputLength'
                AND answer_key ? 'roundingInstruction'
                AND jsonb_typeof(answer_key -> 'expectedAnswer') = 'string'
                AND jsonb_typeof(answer_key -> 'requiredInputLength') = 'number'
                AND answer_key -> 'requiredInputLength' = '4'::jsonb
                AND jsonb_typeof(answer_key -> 'roundingInstruction') = 'string'
                AND LENGTH(TRIM(answer_key ->> 'roundingInstruction')) > 0
                AND LENGTH(answer_key ->> 'expectedAnswer') = 4
                AND answer_key ->> 'expectedAnswer' ~ '^-?[0-9]+([.][0-9]+)?$'
            )
        ),
    -- Question position is LOCAL within its section (no global version position uniqueness).
    CONSTRAINT uk_exam_questions_section_position UNIQUE (exam_section_id, position),
    -- A source question may appear at most once per version.
    CONSTRAINT uk_exam_questions_version_source UNIQUE (exam_version_id, source_question_id)
);
-- (No separate (exam_version_id) index: leftmost prefix of uk_exam_questions_version_source covers it.)
CREATE INDEX idx_exam_questions_source
    ON exam_questions (source_question_id);

-- 6. EXAM_QUESTION_OPTIONS (snapshot of choices; correctness in is_correct)
CREATE TABLE exam_question_options (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_question_id BIGINT      NOT NULL,
    option_key       VARCHAR(20) NOT NULL,
    content          TEXT        NOT NULL,
    is_correct       BOOLEAN     NOT NULL DEFAULT FALSE,
    position         INTEGER     NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_options_question
        FOREIGN KEY (exam_question_id) REFERENCES exam_questions(id) ON DELETE CASCADE,
    CONSTRAINT chk_exam_options_key CHECK (option_key IN ('A','B','C','D','E','F')),
    CONSTRAINT chk_exam_options_position CHECK (position >= 0),
    CONSTRAINT chk_exam_options_content_not_blank CHECK (LENGTH(TRIM(content)) > 0),
    CONSTRAINT uk_exam_options_question_key UNIQUE (exam_question_id, option_key),
    CONSTRAINT uk_exam_options_question_position UNIQUE (exam_question_id, position)
);

-- 7. EXAM_SESSIONS (a sitting; pins one PUBLISHED exam version)
CREATE TABLE exam_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT       NOT NULL,
    exam_version_id   BIGINT       NOT NULL,
    owner_teacher_id  BIGINT       NOT NULL,
    code              VARCHAR(30)  NOT NULL,
    title             VARCHAR(255) NOT NULL,
    status            VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
    starts_at         TIMESTAMPTZ  NOT NULL,
    ends_at           TIMESTAMPTZ  NOT NULL,
    max_attempts      INTEGER      NOT NULL DEFAULT 1,
    created_by        BIGINT       NOT NULL,
    opened_at         TIMESTAMPTZ,
    closed_at         TIMESTAMPTZ,
    version           INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Composite FK: pinned exam version MUST be in the SAME school (and PUBLISHED via service).
    CONSTRAINT fk_exam_sessions_version_school
        FOREIGN KEY (school_id, exam_version_id) REFERENCES exam_versions(school_id, id) ON DELETE RESTRICT,
    -- Composite FK: owner teacher MUST be in the SAME school.
    CONSTRAINT fk_exam_sessions_owner_school
        FOREIGN KEY (school_id, owner_teacher_id) REFERENCES teacher_profiles(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_sessions_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_sessions_status
        CHECK (status IN ('DRAFT','SCHEDULED','OPEN','CLOSED','CANCELLED')),
    CONSTRAINT chk_exam_sessions_window CHECK (ends_at > starts_at),
    CONSTRAINT chk_exam_sessions_max_attempts CHECK (max_attempts > 0),
    CONSTRAINT chk_exam_sessions_version_col CHECK (version >= 0),
    CONSTRAINT chk_exam_sessions_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_exam_sessions_title_not_blank CHECK (LENGTH(TRIM(title)) > 0),
    -- M1: status<->timestamps invariant (frozen state machine, defense-in-depth).
    -- DRAFT/SCHEDULED: no timestamps. OPEN: opened_at set, closed_at NULL.
    -- CLOSED: both set. CANCELLED: none (reachable only from DRAFT/SCHEDULED).
    CONSTRAINT chk_exam_sessions_state_timestamps CHECK (
        (status IN ('DRAFT','SCHEDULED') AND opened_at IS NULL AND closed_at IS NULL)
        OR (status = 'OPEN' AND opened_at IS NOT NULL AND closed_at IS NULL)
        OR (status = 'CLOSED' AND opened_at IS NOT NULL AND closed_at IS NOT NULL)
        OR (status = 'CANCELLED' AND opened_at IS NULL AND closed_at IS NULL)
    ),
    -- Composite-FK target for exam_session_participants.exam_session_id.
    CONSTRAINT uk_exam_sessions_school_id UNIQUE (school_id, id)
);
-- Session code is OWNER-scoped (two teachers in the same school may share a code).
CREATE UNIQUE INDEX uk_exam_sessions_owner_code_ci
    ON exam_sessions (owner_teacher_id, LOWER(code));
CREATE INDEX idx_exam_sessions_owner_created
    ON exam_sessions (owner_teacher_id, created_at);
CREATE INDEX idx_exam_sessions_status_starts
    ON exam_sessions (status, starts_at);

-- 8. EXAM_SESSION_PARTICIPANTS (explicit student roster; no classroom expansion)
CREATE TABLE exam_session_participants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           BIGINT      NOT NULL,
    exam_session_id     BIGINT      NOT NULL,
    student_profile_id  BIGINT      NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'ELIGIBLE',
    added_by            BIGINT      NOT NULL,
    added_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    blocked_at          TIMESTAMPTZ,
    version             INTEGER     NOT NULL DEFAULT 0,
    -- Composite FK: session MUST be in the SAME school (CASCADE on session delete).
    CONSTRAINT fk_exam_session_participants_session_school
        FOREIGN KEY (school_id, exam_session_id) REFERENCES exam_sessions(school_id, id) ON DELETE CASCADE,
    -- Composite FK: student MUST be in the SAME school (cross-school blocked at DB level).
    CONSTRAINT fk_exam_session_participants_student_school
        FOREIGN KEY (school_id, student_profile_id) REFERENCES student_profiles(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_session_participants_added_by
        FOREIGN KEY (added_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_exam_session_participants_status CHECK (status IN ('ELIGIBLE','BLOCKED')),
    CONSTRAINT chk_exam_session_participants_version CHECK (version >= 0),
    -- M2: status<->blocked_at invariant. Both operands are non-null booleans, so plain equality
    -- is a clean two-valued comparison (no NULL three-valued logic pitfall).
    CONSTRAINT chk_exam_session_participants_blocked CHECK (
        (status = 'ELIGIBLE') = (blocked_at IS NULL)
    ),
    CONSTRAINT uk_exam_session_participants_session_student
        UNIQUE (exam_session_id, student_profile_id)
);
CREATE INDEX idx_exam_session_participants_session_status
    ON exam_session_participants (exam_session_id, status);
CREATE INDEX idx_exam_session_participants_student
    ON exam_session_participants (student_profile_id);

-- ============================================================
-- PURPOSE SEED
-- Seed the 4 default exam purposes for every school that exists at migration time.
-- Idempotent (WHERE NOT EXISTS on case-insensitive code). Safe on a clean DB
-- with no schools (CROSS JOIN yields 0 rows). DemoDataSeeder ensures the same
-- 4 purposes for demo schools created after Flyway (see design report).
-- ============================================================
INSERT INTO exam_purposes (school_id, code, title, position)
SELECT s.id, v.code, v.title, v.position
FROM schools s
CROSS JOIN (VALUES
    ('MIDTERM',  'Giữa kỳ',      0),
    ('FINAL',    'Cuối kỳ',      1),
    ('QUIZ',     'Bài kiểm tra', 2),
    ('PRACTICE', 'Luyện tập',    3)
) AS v(code, title, position)
WHERE NOT EXISTS (
    SELECT 1
    FROM exam_purposes p
    WHERE p.school_id = s.id
      AND LOWER(p.code) = LOWER(v.code)
);
