-- ============================================================
-- Quizopia Flyway Migration V8
-- Purpose: Classrooms — class-based session visibility.
--   - classrooms                (teacher-owned, school-scoped)
--   - classroom_members         (student roster per classroom)
--   - exam_session_classes      (session <-> classroom junction)
--
-- NOTE: exam_sessions.visibility column absorbed into V8 CREATE TABLE.
--       Permission grants absorbed into V3 role-permission seed.
--
-- Design (see .claude/docs/brainstorm-classes-system-design.md):
--   - Classes REPLACE explicit participants as the visibility gatekeeper.
--     The legacy exam_session_participants table/endpoints stay (dead code,
--     no DROP) but no longer drive availability or start authorization.
--   - School scope enforced via composite FKs + UNIQUE (school_id, id)
--     targets, exactly like V6/V7/V8.
--   - PK = BIGINT GENERATED BY DEFAULT AS IDENTITY (consistent with V2+).
--
-- Do not modify V1–V9. Do not modify this file after it has been applied.
-- ============================================================

-- 1. CLASSROOMS (teacher-owned; school-scoped)
CREATE TABLE classrooms (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT       NOT NULL,
    owner_teacher_id  BIGINT       NOT NULL,
    code              VARCHAR(30)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       VARCHAR(500),
    status            VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_classrooms_school
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    -- Composite FK: owner teacher MUST be in the SAME school.
    CONSTRAINT fk_classrooms_teacher_school
        FOREIGN KEY (school_id, owner_teacher_id) REFERENCES teacher_profiles(school_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_classrooms_status CHECK (status IN ('ACTIVE','ARCHIVED')),
    CONSTRAINT chk_classrooms_code_not_blank CHECK (LENGTH(TRIM(code)) > 0),
    CONSTRAINT chk_classrooms_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
    -- Composite-FK target for classroom_members.classroom_id / exam_session_classes.classroom_id.
    CONSTRAINT uk_classrooms_school_id UNIQUE (school_id, id)
);
-- Classroom code is OWNER-scoped (two teachers in the same school may share a code).
CREATE UNIQUE INDEX uk_classrooms_owner_code_ci
    ON classrooms (school_id, owner_teacher_id, LOWER(code));
CREATE INDEX idx_classrooms_owner_created
    ON classrooms (owner_teacher_id, created_at);

-- 2. CLASSROOM_MEMBERS (student roster; same-school enforced)
CREATE TABLE classroom_members (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id        BIGINT      NOT NULL,
    student_profile_id  BIGINT      NOT NULL,
    school_id           BIGINT      NOT NULL,
    added_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_classroom_members_classroom
        FOREIGN KEY (classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,
    -- Composite FK: student MUST be in the SAME school as the classroom.
    CONSTRAINT fk_classroom_members_student_school
        FOREIGN KEY (school_id, student_profile_id) REFERENCES student_profiles(school_id, id) ON DELETE RESTRICT,
    -- One membership per (classroom, student).
    CONSTRAINT uk_classroom_members_classroom_student UNIQUE (classroom_id, student_profile_id),
    -- Composite-FK target (reserved).
    CONSTRAINT uk_classroom_members_classroom_id UNIQUE (classroom_id, id)
);
CREATE INDEX idx_classroom_members_classroom
    ON classroom_members (classroom_id);
CREATE INDEX idx_classroom_members_student
    ON classroom_members (student_profile_id);

-- 3. EXAM_SESSION_CLASSES (session <-> classroom junction; pure M2M, no entity)
CREATE TABLE exam_session_classes (
    exam_session_id  BIGINT NOT NULL,
    classroom_id     BIGINT NOT NULL,
    school_id        BIGINT NOT NULL,
    CONSTRAINT pk_exam_session_classes PRIMARY KEY (exam_session_id, classroom_id),
    -- Composite FK: session MUST be in the SAME school (CASCADE on session delete).
    CONSTRAINT fk_esc_session_school
        FOREIGN KEY (school_id, exam_session_id) REFERENCES exam_sessions(school_id, id) ON DELETE CASCADE,
    -- Composite FK: classroom MUST be in the SAME school (CASCADE on classroom delete).
    CONSTRAINT fk_esc_classroom_school
        FOREIGN KEY (school_id, classroom_id) REFERENCES classrooms(school_id, id) ON DELETE CASCADE
);
CREATE INDEX idx_esc_classroom
    ON exam_session_classes (classroom_id);
